class SearchAgent(MulliganAgent):
    
    def breadthFirstSearch(self, startState):                      ...
    def getChildren(self, state):                                  ...
    def combatMaxMin(self, state):                                 ...
    def chooseBlockers(self, legalActions, combatPairings, state): ...
    def chooseBlockOrder(self, combatPairingsIDs, game):           ...
    . . .
